import About from "./About/About";
import Awards from "./Awards/Awards";
import Chef from "./Chef/Chef";
import FindUs from "./FindUs/FindUs";
import Footer from "./Footer/Footer";
import Gallery from "./Gallery/Gallery";
import Header from "./Header/Header";
import Prices from "./Prices/Prices";
import Video from "./Video/Video";
import Newsletter from "./Newsletter/Newsletter";
export { About, Awards, Chef, FindUs, Footer, Gallery, Header, Prices, Video, Newsletter };
